baseURL: http://example.org/
languageCode: en-us
title: Intisar Bin Naim
theme: gokarna

enableRobotsTXT: true
menu:
  main:
    - identifier: posts
      url: /posts/
      pre: ""
      post: ""
      name: Posts
      weight: 1
