baseURL: https://
languageCode: en-us
title: Intisar Bin Naim
theme: gokarna

enableRobotsTXT: true
menu:
  main:
    - identifier: posts
      url: /content/posts/
      pre: ""
      post: ""
      name: Posts
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: github
      url: https://github.com/showmik
      weight: 3
      pre: <span data-feather='github'></span>

    - params:
      avatarURL: /images/avatar.jpg