baseURL: https://
languageCode: en-us
title: Intisar Bin Naim
theme: gokarna
defaultContentLanguage: en
enableEmoji: true
enableRobotsTXT: true
pygmentsStyle: monokai
menu:
  main:
    - identifier: posts
      url: /intisarbnaim.com/posts/
      pre: ""
      post: ""
      name: Posts
      weight: 1
    - identifier: tags
      name: Tags
      url: /intisarbnaim.com/tags/
      weight: 2
    - identifier: github
      url: https://github.com/showmik
      weight: 3
      pre: <span data-feather='github'></span>

params:
  avatarURL: "/images/avatar.jpg"
  avatarSize: "size-m"
  description: Learning is earning.
  accentColor: "#FF4D4D"

  socialIcons:
    - name: twitter
      url: https://twitter.com/showmik_h
    - name: linkedin
      url: https://www.linkedin.com/in/intisarbn/
    - name: stackoverflow
      url: https://example.com
    - name: instagram
      url: https://www.instagram.com/showmik.h/
    - name: email
      url: mailto:showmik.haque@gmail.com

  metaKeywords:
    - blog
  footer: Intisar Bin Naim