baseURL: https://intisarbnaim.com
theme: LoveIt
title: Intisar Bin Naim
defaultContentLanguage: en
languageCode: en
languageName: English
hasCJKLanguage: false
paginate: 12
googleAnalytics: UA-236106105-1
copyright: ""
enableRobotsTXT: true
enableGitInfo: false
enableEmoji: true
ignoreErrors:
  - error-remote-getjson
  - error-missing-instagram-accesstoken
author:
  name: Intisar Bin Naim
  email: intisarbnaim@gmail.com
  link: https://intisarbnaim.com

taxonomies:
  tag: tags
  category: categories

menu:
  main:
    - weight: 1
      identifier: posts
      pre: ""
      post: ""
      name: Posts
      url: /posts/
      title: ""
    - weight: 2
      identifier: projects
      pre: ""
      post: ""
      name: Projects
      url: /projects/
      title: ""
    - weight: 3
      identifier: tags
      pre: ""
      post: ""
      name: Tags
      url: /tags/
      title: ""
    - weight: 4
      identifier: categories
      pre: ""
      post: ""
      name: Categories
      url: /categories/
      title: ""
    
params:
  defaultTheme: light
  gitRepo: https://github.com/showmik/blog
  fingerprint: ""
  dateFormat: 02-01-2006
  title: Intisar Bin Naim
  description: It's time to meet the geek.
  images:
    - /logo.png
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ""
      name: intisarbnaim
      pre: <i class="fa-regular fa-at"></i>
      post: ""
      typeit: false
  footer:
    enable: true
    custom: ""
    hugo: false
    copyright: true
    author: true
    since: 2022
    icp: ""
    license: false
  section:
    paginate: 20
    dateFormat: January 02
    rss: 10
  list:
    paginate: 20
    dateFormat: January 02
    rss: 10
  app:
    title: Intisar Bin Naim
    noFavicon: false
    svgFavicon: ""
    themeColor: "#ffffff"
    iconColor: "#5bbad5"
    tileColor: "#da532c"
  search:
    enable: true
    type: algolia
    contentLength: 4000
    placeholder: ""
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ""
      appID: ""
      searchKey: ""
  home:
    rss: 10
    profile:
      enable: true
      gravatarEmail: ""
      avatarURL: /images/avatar.png
      title: ""
      subtitle: A Clean, Elegant but Advanced Hugo Theme
      typeit: true
      social: true
      disclaimer: ""
    posts:
      enable: true
      paginate: 6
  social:
    GitHub: showmik
    Linkedin: intisarbnaim
    Twitter: showmik_h
    Instagram: showmik.h
    Facebook: showmik1
    Telegram: intisarbnaim
   
  page:
    hiddenFromHomePage: false
    hiddenFromSearch: false
    twemoji: false
    lightgallery: false
    ruby: true
    fraction: true
    fontawesome: true
    linkToMarkdown: true
    rssFullText: false
    toc:
      enable: true
      keepStatic: false
      auto: true
    code:
      copy: true
      maxShownLines: 50
    math:
      enable: false
      inlineLeftDelimiter: ""
      inlineRightDelimiter: ""
      blockLeftDelimiter: ""
      blockRightDelimiter: ""
      copyTex: true
      mhchem: true
    mapbox:
      accessToken: pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
      darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
      navigation: true
      geolocate: true
      scale: true
      fullscreen: true
    share:
      enable: true
      Twitter: true
      Facebook: true
      Linkedin: true
      Whatsapp: true
      Pinterest: false
      Tumblr: false
      HackerNews: false
      Reddit: true
      VK: false
      Buffer: false
      Xing: false
      Line: false
      Instapaper: false
      Pocket: false
      Flipboard: false
      Weibo: false
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Mix: false
    comment:
      enable: false
      disqus:
        enable: false
        shortname: ""
      gitalk:
        enable: false
        owner: ""
        repo: ""
        clientId: ""
        clientSecret: ""
      valine:
        enable: false
        appId: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI
        appKey: WBmoGyJtbqUswvfLh6L8iEBr
        placeholder: ""
        avatar: mp
        meta: ""
        pageSize: 10
        lang: ""
        visitor: true
        recordIP: true
        highlight: true
        enableQQ: false
        serverURLs: https://leancloud.hugoloveit.com
        emoji: ""
      facebook:
        enable: false
        width: 100%
        numPosts: 10
        appId: ""
        languageCode: ""
      telegram:
        enable: false
        siteID: ""
        limit: 5
        height: ""
        color: ""
        colorful: true
        dislikes: false
        outlined: false
      commento:
        enable: false
      utterances:
        enable: false
        repo: ""
        issueTerm: pathname
        label: ""
        lightTheme: github-light
        darkTheme: github-dark
      giscus:
        enable: false
        repo: ""
        repoId: ""
        category: Announcements
        categoryId: ""
        lang: ""
        mapping: pathname
        reactionsEnabled: "1"
        emitMetadata: "0"
        inputPosition: bottom
        lazyLoading: false
        lightTheme: light
        darkTheme: dark
    library:
      css: {}
      js: {}
    seo:
      images: []
      publisher:
        name: Intisar Bin Naim
        logoUrl: /images/avatar.png
  typeit:
    speed: 100
    cursorSpeed: 1000
    cursorChar: "|"
    duration: -1
  verification:
    google: ""
    bing: ""
    yandex: ""
    pinterest: ""
    baidu: ""
  seo:
    image: /images/Apple-Devices-Preview.png
    thumbnailUrl: /images/screenshot.png
  analytics:
    enable: false
    google:
      id: ""
      anonymizeIP: true
    fathom:
      id: ""
      server: ""
    plausible:
      dataDomain: ""
    yandexMetrica:
      id: ""
  cookieconsent:
    enable: false
    content:
      message: ""
      dismiss: ""
      link: ""
  cdn:
    data: jsdelivr.yml
  compatibility:
    polyfill: false
    objectFit: false
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
privacy:
  googleAnalytics: {}
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
mediaTypes:
  text/plain:
    suffixes:
      - md
outputFormats:
  MarkDown:
    mediaType: text/plain
    isPlainText: true
    isHTML: false
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
languages:
  en:
    weight: 1
    languageCode: en
    languageName: English
    hasCJKLanguage: false
    copyright: This work is licensed under a Creative Commons
      Attribution-NonCommercial 4.0 International License.
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ""
          post: ""
          name: Posts
          url: /posts/
          title: ""
        - weight: 2
          identifier: projects
          pre: ""
          post: ""
          name: Projects
          url: /projects/
          title: ""
        - weight: 3
          identifier: tags
          pre: ""
          post: ""
          name: Tags
          url: /tags/
          title: tag
        - weight: 4
          identifier: categories
          pre: ""
          post: ""
          name: Categories
          url: /categories/
          title: ""
        - weight: 5
          identifier: github
          pre: <i class='fab fa-github fa-fw' aria-hidden='true'></i>
          post: ""
          name: ""
          url: https://github.com/showmik
          title: GitHub
    params:
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ""
        maxResultLength: 10
        snippetLength: 30
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.en
          appID: TRVL8DOQN7
          searchKey: 2904157de91bbcda8744a8029fe1e7a0
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ""
          avatarURL: /images/avatar.png
          title: ""
          subtitle: It’s time to meet the geek.
          typeit: true
          social: true
          disclaimer: ""
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: showmik
        Linkedin: intisarbnaim
        Twitter: showmik_h
        Instagram: showmik.h
        Facebook: showmik1
        Telegram: intisarbnaim
        Email: showmik.haque@gmail.com

  bn:
    weight: 2
    languageCode: bn
    languageName: বাংলা
    hasCJKLanguage: false
    copyright: This work is licensed under a Creative Commons
      Attribution-NonCommercial 4.0 International License.
    menu:
      main:
        - weight: 1
          identifier: posts
          pre: ""
          post: ""
          name: পোস্ট
          url: /posts/
          title: ""
        - weight: 2
          identifier: projects
          pre: ""
          post: ""
          name: প্রজেক্ট
          url: /projects/
          title: ""
        - weight: 3
          identifier: tags
          pre: ""
          post: ""
          name: ট্যাগ
          url: /tags/
          title: ""
        - weight: 4
          identifier: categories
          pre: ""
          post: ""
          name: ক্যাটাগরি
          url: /categories/
          title: ""
        - weight: 5
          identifier: github
          pre: <i class='fab fa-github fa-fw' aria-hidden='true'></i>
          post: ""
          name: ""
          url: https://github.com/showmik
          title: GitHub
    params:
      search:
        enable: true
        type: algolia
        contentLength: 4000
        placeholder: ""
        maxResultLength: 10
        snippetLength: 50
        highlightTag: em
        absoluteURL: false
        algolia:
          index: index.bn
          appID: TRVL8DOQN7
          searchKey: 2904157de91bbcda8744a8029fe1e7a0
      home:
        rss: 10
        profile:
          enable: true
          gravatarEmail: ""
          avatarURL: /images/avatar.png
          subtitle: শেখার চেষ্টায় আছি...
          typeit: true
          social: true
          disclaimer: ""
        posts:
          enable: true
          paginate: 6
      social:
        GitHub: showmik
        Linkedin: intisarbnaim
        Twitter: showmik_h
        Instagram: showmik.h
        Facebook: showmik1
        Telegram: intisarbnaim
        Email: showmik.haque@gmail.com
